# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'Bezpieczny Kod'
tagline:          'Blog'
description:      'Pomagamy zapewniać bezpieczeństwo na każdym etapie cyklu wytwórczego.'
url:              https://blog.bezpiecznykod.pl
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5
excerpt_separator: <!--more-->

# Custom vars
version:          3.0

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate]
